In [6]:
import numpy as np
массив = np.arange(50, 101)
print(массив)

[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


In [7]:
import numpy as np

ones = np.ones(10)
zeros = np.zeros(10)
sixes = np.full(10, 6)

массив = np.concatenate((ones, zeros, sixes))

print(массив)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 6. 6. 6. 6.
 6. 6. 6. 6. 6. 6.]


In [8]:
import numpy as np

start_value = 20
end_value = 32
num_rows = 3
num_cols = 4

массив = np.arange(start_value, end_value, (end_value - start_value) / (num_rows * num_cols)).reshape(num_rows, num_cols)

print(массив)

[[20. 21. 22. 23.]
 [24. 25. 26. 27.]
 [28. 29. 30. 31.]]


In [9]:
import numpy as np

массив = np.identity(3)

print(массив)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
import numpy as np

массив = np.zeros((5, 5))

np.fill_diagonal(массив, np.arange(1, 6))

print(массив)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [11]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

total_sum = 0
column_sums = [0] * len(matrix[0])
row_sums = [0] * len(matrix)

for i in range(len(matrix)):
    for j in range(len(matrix[i])):
        total_sum += matrix[i][j]
        column_sums[j] += matrix[i][j]
        row_sums[i] += matrix[i][j]

print("Нийт элементүүдийн нийлбэр:", total_sum)
print("Нийт баганын нийлбэр:", column_sums)
print("Нийт мөрийн нийлбэр:", row_sums)


Нийт элементүүдийн нийлбэр: 45
Нийт баганын нийлбэр: [12, 15, 18]
Нийт мөрийн нийлбэр: [6, 15, 24]


In [16]:
import numpy as np

#Salaries
ChristianoRonaldo_Salary = [34526148, 30513678, 29326744, 35366456, 36605910, 60302591, 60302591, 60302591, 32498507, 32498507]
LionelMessi_Salary = [21574904, 31122902, 29904455, 40208730, 41616246, 74325228, 74577321, 74577321, 66846489, 66846489]
Neymar_Salary = [13171825, 11585744, 17772511, 30062013, 45481662, 45481662, 45481662, 59199687, 59199687, 59199687]
RobertLewandowski_Salary = [4936809, 7804359, 7433747, 15031006, 16596080, 16753638, 24158850, 24158850, 24158850, 21879515]
KarimBenzema_Salary = [10419817, 14348256, 13791552, 16627591, 17215807, 17373365, 19032973, 19043476, 25209235, 25209235]
RiyadMahrez_Salary = [315519, 1104318, 2839675, 6310390, 6310390, 7572468, 7572468, 7572468, 7572468, 10096624]
HarryKane_Salary = [315519, 3155195, 3155195, 6310390, 6310390, 12620780, 12620780, 12620780, 12620780, 12620780]
LukaModric_Salary = [8455598, 8035444, 7730832, 14894456, 15409145, 19579173, 22982419, 22982419, 22982419, 22982419]
KevinDeBruyne_Salary = [4936809, 4338089, 9465585, 9465585, 11043182, 22086364, 22086364, 25241559, 25241559, 25241559]
MohamedSalah_Salary = [1893117, 1827670, 5272932, 6512386, 7572468, 12620780, 12620780, 12620780, 12620780, 22086364]

Salary = np.array([ChristianoRonaldo_Salary, LionelMessi_Salary, Neymar_Salary, RobertLewandowski_Salary, KarimBenzema_Salary, RiyadMahrez_Salary, HarryKane_Salary, LukaModric_Salary, KevinDeBruyne_Salary, MohamedSalah_Salary])
print("Цалин:")
print(Salary)

#Games 
ChristianoRonaldo_Games = [30, 35, 36, 29, 27, 31, 33, 33, 31, 26]
LionelMessi_Games = [31, 38, 33, 34, 36, 34, 33, 35, 26, 32]
Neymar_Games = [26, 33, 34, 30, 20, 17, 15, 18, 22, 20]
RobertLewandowski_Games = [33, 31, 32, 33, 30, 33, 31, 29, 34, 34]
KarimBenzema_Games = [35, 29, 27, 29, 32, 36, 37, 34, 32, 24]
RiyadMahrez_Games = [19, 30, 37, 36, 36, 27, 33, 27, 28, 30]
HarryKane_Games = [10, 34, 38, 30, 37, 28, 29, 35, 37, 38]
LukaModric_Games = [34, 16, 32, 25, 26, 34, 31, 35, 28, 33]
KevinDeBruyne_Games = [16, 34, 27, 36, 37, 19, 35, 25, 30, 32]
MohamedSalah_Games = [28, 19, 34, 31, 36, 38, 34, 37, 35, 38]

Games = np.array([ChristianoRonaldo_Games, LionelMessi_Games, Neymar_Games, RobertLewandowski_Games, KarimBenzema_Games, RiyadMahrez_Games, HarryKane_Games, LukaModric_Games, KevinDeBruyne_Games, MohamedSalah_Games])
print("\nТоглолт:")
print(Games)

salary_column_sum = np.sum(Salary, axis=0)
salary_row_sum = np.sum(Salary, axis=1)

games_column_sum = np.sum(Games, axis=0)
games_row_sum = np.sum(Games, axis=1)

print("\nЦалин мөр:")
print(salary_column_sum)
print("\nЦалин багана:")
print(salary_row_sum)

print("\nТоглолт мөр:")
print(games_column_sum)
print("\nТоглолт багана:")
print(games_row_sum)

Цалин:
[[34526148 30513678 29326744 35366456 36605910 60302591 60302591 60302591
  32498507 32498507]
 [21574904 31122902 29904455 40208730 41616246 74325228 74577321 74577321
  66846489 66846489]
 [13171825 11585744 17772511 30062013 45481662 45481662 45481662 59199687
  59199687 59199687]
 [ 4936809  7804359  7433747 15031006 16596080 16753638 24158850 24158850
  24158850 21879515]
 [10419817 14348256 13791552 16627591 17215807 17373365 19032973 19043476
  25209235 25209235]
 [  315519  1104318  2839675  6310390  6310390  7572468  7572468  7572468
   7572468 10096624]
 [  315519  3155195  3155195  6310390  6310390 12620780 12620780 12620780
  12620780 12620780]
 [ 8455598  8035444  7730832 14894456 15409145 19579173 22982419 22982419
  22982419 22982419]
 [ 4936809  4338089  9465585  9465585 11043182 22086364 22086364 25241559
  25241559 25241559]
 [ 1893117  1827670  5272932  6512386  7572468 12620780 12620780 12620780
  12620780 22086364]]

Тоглолт:
[[30 35 36 29 27 31 33 33 31 26]